#Pthin Tuples
# Python Tuples are represented by ()
# Python tuples are ordered and Unchangeable
print ()
print ("  *****************************")
print ("  *      Pythyon TUPLES       *")
print ("  *****************************")
print ()
thistuple = ("apple", "orange", "banana", "mango")
print (thistuple)
print ()
print ("ACCESS TUPLE ITEMS:")
print ("-------------------")
print ()
print ("*------------------------------------------------*")
print (" NOTE:Access Tuple by identifying its index number")
print ("*------------------------------------------------*")
print ()
mytuple = ("apple", "orange", "banana", "mango")
print (mytuple)
print (mytuple[0])
print (mytuple[1])
print ()
print ("CHANGE TUPLE ITEMS:")
print ("-------------------")
print ()
print ("*----------------------------------*")
print (" NOTE: Tuple values are Unchangeable")
print ("*----------------------------------*")
print ()
"""
##PRODUCES AN ERROR IF WANT TO CHANGE THE TUPLE ITEMS ##

chngtuple = ("apple", "orange", "banana")
thistuple[1] = "none"
print (thistuple)

"""
print ()
print ("LOOPING THROUGH TUPLE ITEMS:")
print ("----------------------------")
print ()
for x in thistuple:
	print (x)
print ()
print ("CHECK IF ITEMS EXISTS:")
print ("----------------------------")
print ()	
# Use 'in' keyword
chcktuple = ("item1", "item2", "item3", "item4")
print (chcktuple)
if "item3" in chcktuple:
	print ("We found the item3 table")
print ()
print ("TUPLE LENGTH:")
print ("-------------")
print ()	
lentuple = ("a", "b", "c" "d")
print (len(lentuple))
print ()
print ("*------------------------------------------------*------------------------------")
print (" NOTE:Once Tuple is created we cant add or modify items, Tuples are Unchangeable")
print ("*------------------------------------------------------------------------------*")
print ()
print (" ADDING ITEM TO TUPLE [Will Generate An Error]:")
print ("-----------------------------------------------")
print ()
'''errtuple = ("1","2","3")
errtuple[2] = "inserted"
print (errtuple) 
print ("1")
'''
print ()
print (" REMOVING ITEM IN TUPLE [Can't Remove but fully Delete]:")
print ("--------------------------------------------------------")
print ()
'''
deltuple = ("a", "b", "c", "c")
print (deltuple)
del deltuple
print (deltuple)'''
print ()
print ("TUPLE CONSTRUCTOR  [ tuple()  ]:")
print ("--------------------------------")
print ()
newtuple = tuple(("1", "2", "3"))
print (type(newtuple))
print (newtuple)
print ()
print ("TUPLE METHODS:")
print ("--------------")
print ()
print ("count() : Returns no of times the specified value occurs")
print ("index() : Searches for the apecified valued based on the index position")
