# Python Modules
print ()
print ("  ************************************")
print ("  *         Python MODULES       *")
print ("  ************************************")
print ()
print ()
print("MODULES:")
print("--------")
print("")
print("MODULE: Same as code library")
print("MODULE:A File containing set of functions that you want to include in your application")
print ()
print("Create a MODULES:")
print("-----------------")
print("")
print(" def greeting(name):")
print("      ('HELLO, ' + name)")
print("  Save it as name.py extension")
print("")
print ()
print("Use a MODULES:")
print("-----------------")
print()
print("import greeting.py")
print("greeting.greeting('jonathan')")
print("Syntax:")
print("-------")
print("module_name.function_name")
print("Variables in modules:")
print("---------------------")
print()
print()
print("import mymodule")
print("a = mymodule.person['age']")
print("print(a)")
print("Renaming a modules:")
print("---------------------")
print()
print()
# We can create an alias when you impport module, by using the as keyword:
import mymodule as mx

a = mx.person["age"]
print(a)
print()
print()
print("Built-in modules:")
print("-----------------")
print()
print()
import platform

x = platform.system()
print(x)
print()
print()
print("using the DIR Function:")
print("-----------------------")
print()
print()
# there is built-in function that lists all the functions that are available
# dir() function
# List all the functions that are belong///////////////////