# Python file open
#
#
print ()
print ("  ******************************")
print ("  *      Python File Open      *")
print ("  ******************************")
print ()
print ()
print("To open a file use the built in function open() function")
print()
print( " read() for reading a file")
print()
f = open("demotxt.txt", "r")
print(f.read())
print()
print()
print () 
print (" PYTHON Read only parts of the file:")
print ("-------------=========--------------")
print ()
# Returns only first 5 characters of the file
f = open("demotxt.txt", "r")
print(f.read(5))
print()
print()
print () 
print (" PYTHON Read Lines:")
print ("-------------------")
print ()
f = open("demotxt.txt", "r")
print(f.readline())
print(f.readline())
print()
print()
print () 
print (" PYTHON Read Lines using for loop:")
print ("----------------------------------")
print ()
f = open("demotxt.txt", "r")
for x in f:
	print(x)
print()
print()
print () 
print (" PYTHON Close Files:")
print ("--------------------")
print ()
# it is better to close the file after opening it
f = open("demotxt.txt", "r")
print(f.readline())
f.close()